import type { DomainErrorCode } from '../domain/errors.js';

const STATUS_BY_CODE: Record<DomainErrorCode, number> = {
  VALIDATION_REQUIRED_FIELD: 400,
  INCOME_EXPENSE_MUTUAL_EXCLUSION: 400,
  ACCOUNT_NOT_FOUND_OR_INACTIVE: 400,
  CATEGORY_NOT_FOUND_OR_INACTIVE: 400,
  CATEGORY_TYPE_MISMATCH: 400,
  ENTRY_NOT_FOUND: 404,
  ENTRY_TRANSFER_IMMUTABLE: 409,
  DUPLICATE_TENANT_NAME: 400,
  DUPLICATE_ACCOUNT_NAME: 400,
  DUPLICATE_CATEGORY_NAME: 400,
  TENANT_NOT_FOUND: 404,
  TENANT_MEMBERSHIP_REQUIRED: 403,
  ACCOUNT_NOT_FOUND: 404,
  CATEGORY_NOT_FOUND: 404,
  TRANSFER_SAME_ACCOUNT: 400,
  TRANSFER_INVALID_AMOUNT: 400,
  TRANSFER_ACCOUNT_UNAVAILABLE: 404,
  TRANSFER_INTEGRITY_VIOLATION: 409,
  EMAIL_ALREADY_REGISTERED: 400,
  INVALID_CREDENTIALS: 401,
  UNAUTHENTICATED: 401,
  NOT_ENTITLED: 403,
  ENTITLEMENT_SERVICE_UNAVAILABLE: 503,
  INVALID_TENANT_CONTEXT: 400,
};

/** api-contract-principles.md #6 — every DomainError maps to a stable HTTP status + machine-readable code. */
export function statusForDomainErrorCode(code: DomainErrorCode): number {
  return STATUS_BY_CODE[code] ?? 500;
}
